server:
  port: 8761

#spring:
#  security:
#    user:
#      name: admin
#      password: pwd

eureka:
  instance:
    hostname: localhost
  server:
    waitTimeInMsWhenSyncEmpty: 5000
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
