server.port: 10000

spring:
  application:
    name: admin-service
  boot.admin.notify:
    slack:
      webhook-url: https://hooks.slack.com/services/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
      channel: prod-incidents
  #      message: "*#{application.name}* (#{application.id}) is *#{to.status}*"

eureka:
  instance:
    hostname: localhost
    preferIpAddress: false
    leaseRenewalIntervalInSeconds: 10
  client:
    registryFetchIntervalSeconds: 5
    registerWithEureka: false
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${EUREKA_SERVER:localhost}:8761/eureka/

management.endpoints.web.exposure.include: "*"
