spring:
  application:
    name: ${APP_SERVICE_NAME:reactive-service}
server.port: ${APP_SERVICE_PORT:10300}
management:
  endpoints.web.exposure.include: "*"
  endpoint:
    health:
      show-details: ALWAYS

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://${EUREKA_SERVER:localhost}:8761/eureka/
  instance:
    hostname: localhost
    preferIpAddress: true

logging:
  level:
    com.netflix.turbine: INFO
  file: logs/${spring.application.name}.log
  pattern:
    file: >-
      %clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%5p) %clr(${PID}){magenta} %clr(---)
      {faint}%clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n%wEx

